name: prox
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:
  get_storage:
  intl:
  package_info:
  device_info:
  sprintf:
  lottie:
  connectivity:
  http:
  dio:
  event_bus:
  path_provider:
  url_launcher:
  app_settings:
  # huawei_hmsavailability:
  flutter_statusbarcolor_ns:
  flutter_inappwebview:
  flutter_keyboard_visibility:
  extended_image:
  auto_size_text: ^3.0.0-nullsafety.0
  vibration: ^1.7.4-nullsafety.0
  version:
  permission_handler: ^8.0.1 # visit the site to setup for each platform.

  # --- listing use ---
  pull_to_refresh:
  flutter_slidable:
  # --- ------- --- ---

  # --- camera use ---
  camera: #^0.8.1
    git:
      url: https://github.com/bottlepay/plugins.git
      path: packages/camera/camera
      ref: android-rework
  pinch_zoom: ^0.1.0
  native_device_orientation: ^1.0.0
  align_positioned: ^2.0.0
  image: ^3.0.2
  image_editor: ^1.0.0
  # --- ------ --- ---

  # --- location use ---
  location:
  huawei_location:
  geocoding:
  google_maps_flutter: ^2.0.3
  huawei_map:
    path: lib/ProX/Download/hms/huawei_map
  # --- -------- --- ---

  # --- notification use ---
  # onesignal_flutter: ^2.6.3
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  huawei_push: ^5.1.1+301
  flutter_fgbg:
  # --- ------------ --- ---

  # list project base plugin here:

  # flutter_html:
  # open_file:
  # flutter_swiper: ^1.1.6
  # smooth_page_indicator: ^0.2.1
  # qr_flutter: ^4.0.0
  # menu_button: ^1.4.2+1
  # pin_code_fields: ^7.0.0
  # flutter_xlider:
  # qr_code_scanner:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/ProX/assets/
    - lib/ProX/assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
